version: 2.1
jobs:
  unit_tests:
    docker:
      - image: cimg/python:3.10.1
    
    steps:
      - checkout

      - run:
          name: Unit Tests for Bias Detector
          command: |
            pip3 install -r requirements.txt
            python3 -m tests.unit.TestBiasDetector

      - run:
          name: Unit Tests for Risk Calculator
          command: |
            python3 -m tests.unit.TestRiskCalculator

workflows:
  version: 2
  test_and_run:
    jobs:
      - unit_tests
